### ISSUE TITLE
'delalltwins' console command requires twin id

### ISSUE THREAD

**Issue by stevebus** [Azure-Samples/digital-twins-explorer#100]
the 'delalltwins' console command (which says it will delete all twins) seems to require a twin id, which doesn't make sense

![image](https://user-images.githubusercontent.com/11857454/108774221-013dd000-7525-11eb-8adb-2c783e32494d.png)

**Comment by jamiewilbraham** [comment]
hi @stevebus ,

This should be now fixed in the development branch

![image](https://user-images.githubusercontent.com/13650672/112928638-7aa78e80-9173-11eb-8e7e-2a3fc759aca5.png)

**Comment by jamiewilbraham** [comment]
Closing as the fix is now in the new default main branch here: https://github.com/Azure-Samples/digital-twins-explorer

Thanks again for reporting!
