### ISSUE TITLE
adt-explorer - Invalid relationship

### ISSUE THREAD

**Issue by disssid** [Azure-Samples/digital-twins-explorer#105]
I'm trying to build device twins model and network for a Water fleet management. I created the JSON models required based on the examples and created a data file as per the format specified. When I try to import the data it says,

`Twin relationship does not align with the model. Please ensure that the relationship is in alignment with the model. See section on listing models http://aka.ms/adtv2models.`

I am using the Network tab of the Developer tools to identify and fix any issues. But when I create this model manually it works completely fine. Its only when I import it gives me the above error.

This is the result when I do it manually,
![image](https://user-images.githubusercontent.com/22083404/110321336-8ce05200-8037-11eb-940c-b5a1a5f0727c.png)

This is the result I'm getting when I upload the data file
![image](https://user-images.githubusercontent.com/22083404/110321066-2f4c0580-8037-11eb-8a15-1372d11e889b.png)

I'm attaching the model files that I created for my requirement
[wsf-models.zip](https://github.com/Azure-Samples/digital-twins-explorer/files/6101264/wsf-models.zip)

Data file
[WaterSupplyFleet.xlsx](https://github.com/Azure-Samples/digital-twins-explorer/files/6101251/WaterSupplyFleet.xlsx)

Also attaching the HAR file of the all the requests and responses during the request
[adt-explorer-har.zip](https://github.com/Azure-Samples/digital-twins-explorer/files/6101278/adt-explorer-har.zip)

Please let me know if you need any other information.

Thanks

**Comment by jamiewilbraham** [comment]
HI @disssid ,

We were getting issues with the files that were provided. We have made a few tweaks and now seems to be working fine.

see attached files. 
[WaterSupplyFleetUpdated.xlsx](https://github.com/Azure-Samples/digital-twins-explorer/files/6225978/WaterSupplyFleetUpdated.xlsx)
[wsf-models.zip](https://github.com/Azure-Samples/digital-twins-explorer/files/6225979/wsf-models.zip)

**Comment by rinisbet** [comment]
Hey @disssid did this solve your issue?

**Comment by disssid** [comment]
@jamiewilbraham @rinisbet 
Apologies guys, I've been working on something else. Yes I did try the files you sent and they are working fine. Thank you so much for the response and fixing the issue.

Looking forward to more updates from you.
