### ISSUE TITLE
local computer adt authentication error

### ISSUE THREAD

**Issue by testjiho** [Azure-Samples/digital-twins-explorer#107]
I met the authentication error on the local computer and fixed it by updating package.json @azure/identity field with recent version. ("@azure/identity": "^1.2.0-beta.2")
Would you check it and update the package.json file for npm install?

**Comment by yglin-nadi** [comment]
I have the same issue here, error messages as 

```
AuthenticationError: ManagedIdentityCredential authentication failed.(status code 400).
More details:
invalid_request(status code 400).
More details:
Identity not found
    at ManagedIdentityCredential.<anonymous> (/home/nadi/adt-explorer/client/node_modules/@azure/identity/dist/index.js:1077:23)
    at Generator.throw (<anonymous>)
    at rejected (/home/nadi/adt-explorer/client/node_modules/@azure/identity/node_modules/tslib/tslib.js:112:69)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

Solved after installed latest @azure/identity 1.2.4

**Comment by BillmanH** [comment]
Confirmed the same issue. Using the Docker image.

**Comment by BillmanH** [comment]
Also confirmed that @testjiho 's solution solves the problem.

**Comment by BillmanH** [comment]
@jamiewilbraham

**Comment by jamiewilbraham** [comment]
Thanks! Will update the package in the next release.

**Comment by jamiewilbraham** [comment]
This has been updated in the dev branch https://github.com/Azure-Samples/digital-twins-explorer/commit/4d12abfe3fb6fc074a480e34cd111f3b9a5fee7a

**Comment by jamiewilbraham** [comment]
Closing as the fix is now in the new default main branch here: https://github.com/Azure-Samples/digital-twins-explorer

Thanks again for reporting!
