### ISSUE TITLE
Make interface inheritance relationships viewable in the graph

### ISSUE THREAD

**Issue by gillermaney** [Azure-Samples/digital-twins-explorer#11]
Feature request: Today, interface inheritance relationships are not viewable in the graph (or the Model View window).  While querying for instance type is straightforward, Interface Inheritance seems to only be encoded in the extends attribute (and informally (?) in @id). This suggests that analytics need to do string parsing to figure out inheritance.  If interface inheritance was displayed as "first class relationship" that was directly queryable, analytics would be simplified.  This suggests that instance to type "lines" could also be optionally shown in the graph and not just displayed in the property explorer window.   It might be nice to allow the Model View to be shown as a flat list or tree...

**Comment by rinisbet** [comment]
This feature is added in 'main'!
