### ISSUE TITLE
Hover-over windows size dictated by description text

### ISSUE THREAD

**Issue by rinisbet** [Azure-Samples/digital-twins-explorer#112]
hover-over window sizing is dictated by the length of the description text

![image](https://user-images.githubusercontent.com/54376482/112357732-08bfd880-8c8d-11eb-86df-be9a69a05463.png)

**Comment by jamiewilbraham** [comment]
@rinisbet ,

Hi there - this should be now fixed in the development branch. Will close once merged to main.

**Comment by jamiewilbraham** [comment]
Closing as the fix is now in the new default main branch here: https://github.com/Azure-Samples/digital-twins-explorer

Thanks again for reporting!
