### ISSUE TITLE
Update sample naming conventions (ADT)

### ISSUE THREAD

**Issue by rinisbet** [Azure-Samples/digital-twins-explorer#113]
We should remove all mentions of the acronym "ADT" in the documentation AND in the product. Namely:
* adt-explorer -> digital-twins-explorer
* Azure_Digital_Twins__ADT__explorer.zip -> Azure_Digital_Twins__explorer.zip
* ADT -> Azure Digital Twins
* AdtExplorerFunctions.zip -> DigitalTwinsExplorerFunctions.zip
* ADT URL -> Azure Digital Twins URL
![image](https://user-images.githubusercontent.com/54376482/112359772-dadb9380-8c8e-11eb-9333-ff94140ff6f7.png)

CC: @cschormann

**Comment by jamiewilbraham** [comment]
HI @rinisbet 

This is updated in the development branch.

**Comment by jamiewilbraham** [comment]
Closing as the fix is now in the new default main branch here: https://github.com/Azure-Samples/digital-twins-explorer

Thanks again for reporting!
