### ISSUE TITLE
local docker adt authentication error in development branch

### ISSUE THREAD

**Issue by AHaryanto** [Azure-Samples/digital-twins-explorer#115]
I encountered an authentication error when running ADT explorer locally with Docker from the development branch. The error message says

```
AggregateAuthenticationError: undefined
Error: EnvironmentCredential is unavailable. Environment variables are not fully configured.
Error: ManagedIdentityCredential - No MSI credential available
Error: Azure CLI could not be found.  Please visit https://aka.ms/azure-cli for installation instructions and then, once installed, authenticate to your Azure account using 'az login'.
Error: Visual Studio Code credential requires the optional dependency 'keytar' to work correctly
    at DefaultAzureCredential.<anonymous> (/usr/src/app/client/node_modules/@azure/identity/dist/index.js:285:29)
    at Generator.throw (<anonymous>)
    at rejected (/usr/src/app/client/node_modules/@azure/identity/node_modules/tslib/tslib.js:115:69)
AggregateAuthenticationError: undefined
```

I had logged in using `az login` and Visual Studio Code before creating the container but no luck.

**Comment by jamiewilbraham** [comment]
Hi @AHaryanto,

Few things I wanted to check:
- Are you using to dockerfile that is provided in the repo?
- Are you authenticating from within the container and not your local environment? Particularly, this step: 
_"A message will appear on the console asking you to login using a code in the Microsoft device login page with your web browser; after doing so the Azure Digital Twins Explorer should start."_


Thanks,
Jamie

**Comment by AHaryanto** [comment]
Hi @jamiewilbraham,

Yes, I'm using the dockerfile from the development branch. 

Huh, that's bizarre. Neither command prompt or `http://localhost:3000` asked me to login after `docker run -it -p3000:3000 azure-digital-twins-explorer`. Below are screenshots of my command prompt and web browser.

![image](https://user-images.githubusercontent.com/41604701/114232305-85f77880-9930-11eb-90e3-263746af94ba.png)
![image](https://user-images.githubusercontent.com/41604701/114232317-8a239600-9930-11eb-95b6-d9c56fb1a53c.png)

**Comment by jamiewilbraham** [comment]
Thanks for the additional information. I just pulled a fresh copy of main to test and could not reproduce your issue. Did you issue the second command in the same console window? You should see something like the below. 


![image](https://user-images.githubusercontent.com/13650672/114785527-f0953200-9dd0-11eb-9e67-f88a4ddbb513.png)

**Comment by AHaryanto** [comment]
I just pulled a fresh copy of main and was able to login using a code in the Microsoft device login page. 

![image](https://user-images.githubusercontent.com/41604701/115129206-c1c9b800-9f98-11eb-9fd8-248dbff40227.png)

![image](https://user-images.githubusercontent.com/41604701/115129157-4e27ab00-9f98-11eb-95dd-739a7d24eb75.png)

![image](https://user-images.githubusercontent.com/41604701/115129165-63043e80-9f98-11eb-9b80-e7e08406083f.png)

Thanks!
