### ISSUE TITLE
Set default branch to main

### ISSUE THREAD

**Issue by aguywithcode** [Azure-Samples/digital-twins-explorer#116]
It looks like the repo has migrated the primary branch from "master" to "main" but the default in Github is still set to "master". 

There is a "Branches" tab under settings and beneath that is an option to set the default branch. 
![image](https://user-images.githubusercontent.com/13209683/113780897-b2b75000-96e4-11eb-9f67-748aac095e2e.png)

**Comment by jamiewilbraham** [comment]
Hi there,

Thanks for reporting!

This is scheduled for tomorrow after we have everything in place to fully retire the master branch.
