### ISSUE TITLE
Issue with auth after computer restart

### ISSUE THREAD

**Issue by alecmanfre** [Azure-Samples/digital-twins-explorer#117]
I've had quite a few issues with auth since starting to use the digital twins explorer. The first time I fired it up, it took multiple tries running `az login` firing up the app, killing the app, trying `az login` again, etc. At some point, it just started working, even though the response I got back from `az login` didn't change. 

After that I didn't have problems, but after restarting my computer, I am having issues again, and I am not sure how to debug it. I am getting this pop-up as soon as the page loads:

<img width="1432" alt="Screen Shot 2021-04-06 at 4 41 52 PM" src="https://user-images.githubusercontent.com/1857204/113782111-47c34480-96f7-11eb-8755-46b8e53801bb.png">

I have tried logging in with `az login` and logging out, and restarting the app.

**Comment by jamiewilbraham** [comment]
hi @alecmanfre ,

Are you working off the master branch? We have made some updates to the auth package on the main branch that might assist with this.

NOTE: main will become the default branch tomorrow after we retire master.

**Comment by alecmanfre** [comment]
I just tried going to main, but unfortunately, I am getting the same error. My domain is the same one I was using before and I am listed as an owner on that domain. 

<img width="723" alt="Screen Shot 2021-04-07 at 10 27 46 AM" src="https://user-images.githubusercontent.com/1857204/113893095-50b22580-978c-11eb-9a3d-3b2299d0ad01.png">

**Comment by alecmanfre** [comment]
I found the issue when trying to add a new user...Our initial subscription had expired on azure, but it wasn't obvious within the portal there was an issue. I have it working now.
