### ISSUE TITLE
Documentation/examples bug

### ISSUE THREAD

**Issue by gillermaney** [Azure-Samples/digital-twins-explorer#12]
Import excel columns are:
- ModelId: The complete dtmi for the model that should be instantiated.
- ID: The unique ID for the twin to be created
- Relationship: A twin id with an outgoing relationship to the new twin
- Relationship name: The name for the outgoing relationship from the twin in the previous column
- Init data: A JSON string that contains Property settings for the twins to be created

However, in the power system example, PowerLine feeds Receiver and the import line is:
dtmi:example:grid:transmission:powerLine;1 | pl_main | p_industry_01 | feeds

There is no relationship from Receiver to PowerLine in the model.  So "Relationship name" is incoming and not outgoing.
-- | -- | -- | --

**Comment by jamiewilbraham** [comment]
Closing as the current example aligns with the desired output.

![image](https://user-images.githubusercontent.com/13650672/117396959-256b5380-af4f-11eb-8d19-0f527eda7b88.png)
