### ISSUE TITLE
Upon running the digital twins explorer initially, graph import is slow

### ISSUE THREAD

**Issue by tasdevani21** [Azure-Samples/digital-twins-explorer#121]
When initially doing a graph import for the first time on the ADT explorer, the explorer seem to be hanging for several minutes and shows the spinning icon. After doing a page refresh and retrying the import the 2nd time, it imports the graph within seconds without any issues. 

Reproduce Steps: Import the existing graph in this example in ADT for the [buildingScenario](https://docs.microsoft.com/en-us/azure/digital-twins/quickstart-adt-explorer#import-the-graph), you may see the first time you try an import, it may hang

Workaround:  Refresh the page and retry the import the 2nd time, this time the visualization preview should come up within seconds without any issues.

**Comment by jamiewilbraham** [comment]
Hi @tasdevani21,

Just wanted to confirm that you have the latest code from the [main](https://github.com/Azure-Samples/digital-twins-explorer/tree/main) branch before we did into this.

Many thanks!

**Comment by tasdevani21** [comment]
> Hi @tasdevani21,
> 
> Just wanted to confirm that you have the latest code from the [main](https://github.com/Azure-Samples/digital-twins-explorer/tree/main) branch before we dig into this.
> 
> Many thanks!

Hi @jamiewilbraham - Yes correct, tested this with both master and main branches and the issue still exists.

**Comment by rinisbet** [comment]
@jamiewilbraham Same question here, did you resolve this?

**Comment by jamiewilbraham** [comment]
@rinisbet - Could not reproduce.

Just tried again. 
- Set up branch new service
- Imported building scenario

Worked the first time fine:
![image](https://user-images.githubusercontent.com/13650672/119581521-d6f6f980-be16-11eb-896a-d5b2521201ed.png)
