### ISSUE TITLE
support for components

### ISSUE THREAD

**Issue by alecmanfre** [Azure-Samples/digital-twins-explorer#123]
i am having trouble uploading a model that has component references. i am trying to bring in models from the opendigitaltwins-building project. when i try upload an object with a component i get the following error: 

![image](https://user-images.githubusercontent.com/1857204/114773272-76af6b00-9d34-11eb-9b93-74ac319bc3c0.png)

i've confirmed that the referenced models are already created and named correctly and when i take out the components it uploads successfully. i saw a note in the documentation that components aren't well handled on the front-end, but it didn't seem that there was a limitation on uploading a model with those components. 

is this something that is on the roadmap for the tool, or something i should think about adding to our own roadmap. thanks!

**Comment by rinisbet** [comment]
@alecmanfre This capability should be fixed in the latest build, have you been able to upload models with components?

**Comment by alecmanfre** [comment]
Yup, it works now!
