### ISSUE TITLE
MFA missing in digital twin connection when using Docker

### ISSUE THREAD

**Issue by BillmanH** [Azure-Samples/digital-twins-explorer#124]
I'm always struggling to access digital twins that are on professional tenants. It seems that I'm able to connect to my personal account's digital twin, but not to any that are on a professional account.

In this case I'm using the Docker implementation and logging in using my work credentials:
![image](https://user-images.githubusercontent.com/10108711/114949488-fce7b200-9e05-11eb-84c3-9710ba48f4bf.png)
The message is telling me that I don't have access to the resource, but according to the portal. I do. 
![image](https://user-images.githubusercontent.com/10108711/114949596-2f91aa80-9e06-11eb-92c6-392c74af09f4.png)

However when I use the Docker version to access my personal account, it works just fine. 
![image](https://user-images.githubusercontent.com/10108711/114949737-797a9080-9e06-11eb-84c3-d3faf045221c.png)
The only difference is my User Access Administrator, but that shouldn't be needed to access the twin, right? 

In each case I'm using the Docker container, which loads the prompts the authentication window, where I use the corresponding credentials for that account. I feel like the access should be the same. 

Any thoughts on what I'm doing wrong here? Authentication is 85% of the work when using the SDK so any troubleshooting tips on this would be appreciated.

**Comment by BillmanH** [comment]
On looking into the issue even closer I found that this issue was with the `az login` tool that the container is running. 

I ran `az login` just to see the process and found that some tenants that I have access to require MFA, which require updating the container to login differently. 
```
The following tenants require Multi-Factor Authentication (MFA). Use 'az login --tenant TENANT_ID' to explicitly login to a tenant.
```
The docker container only runs `az login` and ther is no option to specify a tenant.  This means that for you the docker image won't work. You can use the regular `npm start` approach by first running:
```
az login --tenant {your tenant}
```
then you go through the steps and should be able to connect.

Some error handling may solve this issue for the docker image

**Comment by BillmanH** [comment]
@jamiewilbraham , do you know where in the code the azure CLI command is run? It must be somewhere in the backend of the node.js app, but I can't find it.  If I did I could modify that line to add the tenant parmam and continue using docker.

**Comment by jamescarpinter** [comment]
For Docker, the `az login` command is run on container start. The Dockerfile creates a startup script with this command.

**Comment by BillmanH** [comment]
Thanks @jamescarpinter , I can see the line in the [dockerfile](https://github.com/Azure-Samples/digital-twins-explorer/blob/main/Dockerfile) here:
```
RUN printf "#!/bin/sh\nset -e\naz login && npm run start" > startup.sh
```
If you change that line to:
```
RUN printf "#!/bin/sh\nset -e\naz login --tenant {your-tenant-id}&& npm run start" > startup.sh
```
then build that container, it will connect just fine. Note that once you have built the container it will only connect to twins that are in that tenant, but you can also build separate containers for different tenants.  And you don't have to install node.js locally, which is nice. 

I imagine that this problem will just go away on it's own eventually, but in the meantime this is a pretty good workaround. Thanks again for helping me find the solution.
