### ISSUE TITLE
"Upload model images" button does not work

### ISSUE THREAD

**Issue by rinisbet** [Azure-Samples/digital-twins-explorer#132]
Using this to upload image files does not do anything...

> What is the intended functionality of this button?

![image](https://user-images.githubusercontent.com/54376482/114955255-1cd0a300-9e11-11eb-8d62-bb5013b7ed89.png)

**Comment by jamiewilbraham** [comment]
HI @rinisbet 

Is the file picker showing for you?

The idea is to multi-select images to attach to models that have a specific filename matching the ID.

There is a note in the [uploading models ](https://github.com/Azure-Samples/digital-twins-explorer#uploading-models)section in the readme:

![image](https://user-images.githubusercontent.com/13650672/114957865-fc0e5900-9eb5-11eb-8df3-bf764ef07352.png)

**Comment by rinisbet** [comment]
I missed that in docs, thank you Jamie
