### ISSUE TITLE
Expansion with complete twins graph bug

### ISSUE THREAD

**Issue by rinisbet** [Azure-Samples/digital-twins-explorer#133]
1. do "select * from digitaltwins" to see your whole graph
2. set expansion mode to anything but "in/out"
3. Set expansion levels to more than 1
4. double click a node that should highlight a subsection of the graph
5. Result: only 1 level of in/out expansion is highlighted (no matter what the expansion settings are)

![image](https://user-images.githubusercontent.com/54376482/115791904-1fd21300-a37e-11eb-8df9-dbab48b9fb73.png)

**Comment by jamiewilbraham** [comment]
Hi @rinisbet ,

The expansion functionality has not been designed to work with highlighting. It is to display additional connected nodes when your query returns a subset of your graph.

The example above won't expand seeing as you already have all of your twins visible.

If you try querying a single twin, then double click it, you will see the graph updates with more twins based on the level of expansion.

Hopefully, that makes sense and please let me know if I have misunderstood the issue.

Thanks!!

**Comment by rinisbet** [comment]
Yes, this was my misunderstanding of expansion. We're good here!
