### ISSUE TITLE
Request for information on event notifications from Azure Digital Twin

### ISSUE THREAD

**Issue by ajithkumars** [Azure-Samples/digital-twins-explorer#138]
Not sure this is the correct place to post this but it would be nice to point where else could this be relevant.
We have noticed something while handling updates on Azure Digital Twin via event notifications. 
Case: We have a digital twin and two azure functions. One azure function updates "value" property with values say numerical 10.
Second azure function listens to ADT updates via EventGrid and handles updates that come in. In this case this would be of type patch either "replace" or "add" and processes these updates. We further query ADT for additional attributes required for our processing. 

An issue we have seen is that if we have two updates say first 10 and then 20. There are cases where we receive an update as patch document with "value" update of 20, but when we query for "value" we get the value 10 instead of 20. (This happens very quickly within few 100 milliseconds.
We are trying to understand why this happens? Is the ADT not yet updated when the patch event notification is sent out towards EventGrid?

(We try to use the latest data in case of updates between receiving the update and processing it, thus trying to use the "value" from the query itself instead of from the event notification.

**Comment by rinisbet** [comment]
Hey @ajithkumars, apologies for the delayed reply! Unfortunately this is not the best forum for answering Azure Digital Twins service questions. Please post your questions to [Microsoft Q&A ](https://docs.microsoft.com/en-us/answers/topics/azure-digital-twins.html) or [StackOverflow ](https://stackoverflow.com/questions/tagged/azure-digital-twins)
