### ISSUE TITLE
Error on model upload

### ISSUE THREAD

**Issue by agabaldon** [Azure-Samples/digital-twins-explorer#14]
Trying ADT Explorer on macOS 10.15.3. When I try to upload one of the example models, I get this error on the browser:

Unhandled Rejection (TypeError): Cannot read property 'on' of undefined
SignalRService.subscribe
src/services/SignalRService.js:41
  38 |     this.connection.on(action, callback);
  39 |   } else {
  40 |     await this.initialize();
> 41 |     this.connection.on(action, callback);
     | ^  42 |   }
  43 | }
  44 | 

Appreciate any help. Thanks!

**Comment by cschormann** [comment]
Hi agabaldon, 
Could you check for me which version of node you are running, please?

Thanks!
    CS

**Comment by humblejay** [comment]
I am getting same error on Windows 10 running Node 12.18.3 when uploading one of the sample models

**Comment by agabaldon** [comment]
I have node version v14.8.0. I think now it may be a proxy issue.

**Comment by Tyler-Angell** [comment]
I ran into this error when the ADT URL provided in the connection didn't start off with `https://`. 

@cschormann - Maybe we could add some validation around the URL textbox and updating the docs to display an example URL.

**Comment by sandervandevelde** [comment]
I ran into the same issue. It seems to be fixed indeed when I use this URL;

`https://[your ADT name].api.wcus.digitaltwins.azure.net`

**Comment by jamescarpinter** [comment]
@Tyler-Angell great idea, we'll work on adding some validation in.

**Comment by jamescarpinter** [comment]
We've added a regular expression to validate the Digital Twins URL. It requires the "https" prefix amongst other things.
