### ISSUE TITLE
Enum properties default value

### ISSUE THREAD

**Issue by rinisbet** [Azure-Samples/digital-twins-explorer#159]
After creating a twin, I noticed the properties that take Enums all showed a default value for the enum. I queried for the twin's values, and those values set to "good" were all uninstantiated (i.e. CO2_level, CO_level)

Moreover, shouldn't there be a color schema for initialized vs uninitialized properties?

![image](https://user-images.githubusercontent.com/54376482/117510675-59d81300-af41-11eb-9a4a-f326a1591d2c.png)

gettwin output:
> { "$dtId": "AirQualityN", "$etag": "W/\"6b5c75ef-2a67-41fc-b88b-0b2f9afd494e\"", "airQualityLevel": { "level": "unhealthy", "$metadata": { "level": { "lastUpdateTime": "2021-05-07T21:32:18.6469211Z" } } }, "CO2_level": { "$metadata": {} }, "CO_level": { "$metadata": {} }, "PM10_level": { "$metadata": {} }, "PM25_level": { "$metadata": {} }, "NO_level": { "$metadata": {} }, "SO2_level": { "$metadata": {} }, "C6H6level": { "$metadata": {} }, "NI_level": { "$metadata": {} }, "AS_level": { "$metadata": {} }, "CD_level": { "$metadata": {} }, "NO2_level": { "$metadata": {} }, "O3_level": { "$metadata": {} }, "PB_level": { "$metadata": {} }, "SH2_level": { "$metadata": {} }, "address": { "$metadata": {} }, "location": { "$metadata": {} }, "$metadata": { "$model": "dtmi:digitaltwins:ngsi_ld:city:AirQualityObserved;1" } }

**Comment by jamiewilbraham** [comment]
@rinisbet - We are finalizing an update on how Enums are displayed in the Property Inspector. It will have a dropdown and one of the options will be "---" to indicate it is unset.

There has been no discussion to add a color schema for set/unset properties. The work "Unset" has been used so far. 

I think this should solve this problem. I will comment again when pushed.

**Comment by rinisbet** [comment]
sweet thanks!

**Comment by rinisbet** [comment]
Latest enum update fixes this
