### ISSUE TITLE
Twin properties are not copy-able 

### ISSUE THREAD

**Issue by rinisbet** [Azure-Samples/digital-twins-explorer#160]
A twin's properties I cannot highlight and copy:
![image](https://user-images.githubusercontent.com/54376482/117511098-0b774400-af42-11eb-94e1-b45bf164f6e6.png)

But for some reason the relationships I can...
![image](https://user-images.githubusercontent.com/54376482/117511138-1c27ba00-af42-11eb-9061-1679e5c9881c.png)

-> All properties should be copyable, even if they aren't editable

**Comment by jamiewilbraham** [comment]
Fix is in main
