### ISSUE TITLE
All relationship properties are editable, but you can't save

### ISSUE THREAD

**Issue by rinisbet** [Azure-Samples/digital-twins-explorer#161]
-> You should not be able to change all properties for relationships - only those that the API allows you to send PATCHes to. 
-> Moreover, for the fields that you can modify, you should have the option to click "save" and actually send these PATCH operations

![image](https://user-images.githubusercontent.com/54376482/117511399-7fb1e780-af42-11eb-9fec-ab096c3078a3.png)

**Comment by jamiewilbraham** [comment]
@rinisbet - These should not be editable so good catch there! The original requirement was for this to just be a view of the relationship. Therefore, I am going to label it as an enhancement.

**Comment by rinisbet** [comment]
editable properties are no longer there
