### ISSUE TITLE
Bottom of the screen is cut off

### ISSUE THREAD

**Issue by rinisbet** [Azure-Samples/digital-twins-explorer#163]
This is not always the case, but many users have reported this and I've finally had it occur on my machine as well

![image](https://user-images.githubusercontent.com/54376482/117727391-ce5abe00-b19c-11eb-9c41-4dd7f2137adf.png)

**Comment by jamiewilbraham** [comment]
I think this occurs when you download a file and then close the downloaded files bar at the bottom of the browser.

**Comment by ccrowley96** [comment]
@rinisbet, I haven't seen this in a while and wasn't able to repo.  Closing this unless we can get another repro!
