### ISSUE TITLE
Components for editing complex properties

### ISSUE THREAD

**Issue by rinisbet** [Azure-Samples/digital-twins-explorer#164]
**Ask**:  customer wants way to modify complex property types (enums, timestamps, etc) in an easier, non-string based way. The current method is difficult and mistake-prone

**Workaround**: string-based editing

**Pri**: P1

**Comment by jamiewilbraham** [comment]
FYI: This functionality is in the backlog

**Comment by ccrowley96** [comment]
Closed via #208
