### ISSUE TITLE
[Deployment] Error upon performing the deployment steps to azure

### ISSUE THREAD

**Issue by perkops** [Azure-Samples/digital-twins-explorer#165]
Hi,

I've been following the "Experimental Features - Running in the cloud" section on how to deploy the Digital Twins Explorer to Azure.

The only change I did was to deploy the files to $web container in the storage account instead of web - and enable static website, in order to access the files - since the guide does not come with any instructions on this matter?!?

However - upon deployment when accessing the static website and entering a digital twins instance uri, I am prompted with the following error:

![image](https://user-images.githubusercontent.com/43060445/117775195-8db18200-b23a-11eb-88a7-f509fada9588.png)

When I check the console window, I can see the following errors:

![image](https://user-images.githubusercontent.com/43060445/117775361-ba659980-b23a-11eb-820e-b45fbe6214ef.png)

Have anyone successfully completed the deployment to Azure Cloud and are able to provide some guidance on this matter?

It might be worth nothing, that I am external to the customers Active Directory - and is experiencing the [404 Sub-Domain not Found error](https://docs.microsoft.com/en-us/azure/digital-twins/troubleshoot-error-404) when e.g. using Azure CLI to contact the DT instance (hence I need to fetch access token described in solution 1, when running locally).

**Comment by perkops** [comment]
> Hi @perkops ,
> 
> Deploying the app as a static website will not work due to the requirement of requests needing to be proxied to get around CORS.
> 
> We suggest the frontend application is deployed as part of an Azure Function to satisfy this requirement. (Note that this is just one example of an implementation).
> 
> Hope that helps

Hi @jamiewilbraham,

Thank you for your reply.

I deployed the static files to a web container instead, and managed to get it working by simply accessing the function host app url.

Not sure I entirely understand how the function app is accessing these files though :)

Do you know of an explanation? or possible an arch. drawing ? :)

**Comment by jamescarpinter** [comment]
If you've set things up as per the experimental features section of the readme, the Azure Function will proxy requests for static content through to the underlying storage account. You can see this configured [here](https://github.com/Azure-Samples/digital-twins-explorer/blob/main/functions/proxies.json) or learn more about the capability [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-proxies).

**Comment by perkops** [comment]
> If you've set things up as per the experimental features section of the readme, the Azure Function will proxy requests for static content through to the underlying storage account. You can see this configured [here](https://github.com/Azure-Samples/digital-twins-explorer/blob/main/functions/proxies.json) or learn more about the capability [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-proxies).

Thanks for your reply 👍🏻
