### ISSUE TITLE
SignalR HubConnection failed to start with status code 400

### ISSUE THREAD

**Issue by chaox7s** [Azure-Samples/digital-twins-explorer#18]
## Description

POST `https://adtexplorer-<uid>.service.signalr.net/client/negotiate?hub=adtexplorer-<uid>&negotiateVersion=1` returns 400 status code

![image](https://user-images.githubusercontent.com/37857662/91462221-86b92e00-e8bc-11ea-8b4f-a603483b5904.png)

![image](https://user-images.githubusercontent.com/37857662/91462331-a6505680-e8bc-11ea-804a-dcc412c1a0d6.png)

The error was invoked by following line:
https://github.com/Azure-Samples/digital-twins-explorer/blob/6c4a2059fa0ca76785d09255b3018cd3fa4726fd/client/src/services/SignalRService.js#L29

## Reproduce

1. Create ADT instance.
2. Deploy both `template.json` and `template-eventgrid.json`.
3. Login into the explorer web app from either cloud or localhost.
4. Open browser console.
5. Run DT query.

**Comment by MatthijsvdVeer** [comment]
I came across the same issue today. By default, this sample uses the ADT instance name as a SignalR hub name, but my ADT instance has a hyphen in it. Turns out SignalR hub names are more restrictive than ADT names.

**Comment by jamescarpinter** [comment]
Great catch! At the very least we need to call this out in our documentation. In parallel, we'll investigate if there's a solution here to support ADT instance names with hyphens.

**Comment by jamescarpinter** [comment]
This issue has been resolved. ADT instance names are now encoded before being turned into SignalR hub names.
