### ISSUE TITLE
[Bug] Twins properties fails and the explorer crashes

### ISSUE THREAD

**Issue by uriel-kluk** [Azure-Samples/digital-twins-explorer#214]
**The new published Explorer is not handling gracefully exceptions on properties**

For a model that use to render correctly, and I was able to see the properties, it now fails.

- Import Model
- Create a Twin
- Click on the twin to see properties

![image](https://user-images.githubusercontent.com/41210115/137175160-0442e6b2-207b-4dff-81aa-9f5bb7a08212.png)

I get the following page:
![image](https://user-images.githubusercontent.com/41210115/137175266-1ff25981-034f-42e6-8ddc-9e05e429a2a1.png)

**Comment by ccrowley96** [comment]
Are you able to attach the model that is breaking the inspector?

**Comment by ccrowley96** [comment]
I think we found a repro - working on a fix now @uriel-kluk.
