### ISSUE TITLE
update a twin a property with enum type

### ISSUE THREAD

**Issue by jthin** [Azure-Samples/digital-twins-explorer#221]
Hello.

Since recently, I cannot update a twin property with enum property.
To reproduce this, you can use [PowerLine.json](https://github.com/Azure-Samples/digital-twins-explorer/blob/main/client/examples/PowerLine.json) and import it in Azure Digital Twins Explorer (https://explorer.digitaltwins.azure.net/).

![image](https://user-images.githubusercontent.com/13431974/138039102-ed59c610-d1d6-42c5-b1e9-277a246ea331.png)

Before, I was able to update an enum property as a string property.

**Comment by ccrowley96** [comment]
Thanks for the submission.  The new property inspector doesn't currently support the reusable `schemas` property on DTDL interfaces.  We're working on adding support for that now.

```ts
"schemas": [
        {
            "@type": "Enum",
            "valueSchema": "string",
            "@id": "dtmi:example:grid:gridTypeEnum;1",
            "enumValues": [
                {
                    "name": "ExtraHighVoltage",
                    "enumValue": "ExtraHighVoltage"
                },
                {
                    "name": "HighVoltage",
                    "enumValue": "HighVoltage"
                },
                {
                    "name": "Distribution",
                    "enumValue": "Distribution"
                }
            ]
        }
    ]
```

**Comment by jthin** [comment]
@ccrowley96  Thank you for this fix. It solves the problem.
![image](https://user-images.githubusercontent.com/13431974/138238156-0f2d7f24-5a94-48cb-aa9a-6b2d1185f708.png)
