### ISSUE TITLE
Changing settings to another Digital Twin

### ISSUE THREAD

**Issue by sandervandevelde** [Azure-Samples/digital-twins-explorer#23]
How can I change or remove the initial Digital twin settings (client id, tenant id, URL) to point the explorer to another ADT?

**Comment by nightscape** [comment]
If you're on chrome, open the `Developer tools`, go to the `Application` tab and `Clear site data`. Should be similar in other browsers.

**Comment by nightscape** [comment]
I noticed it's even simpler than that: In the top right, there's a `Sign in` button (a magnifying glass with a key).
Clicking on that will let you enter new credentials.

**Comment by cschormann** [comment]
Yes, if you go to the sign-in button you can enter new credentials.

**Comment by jamescarpinter** [comment]
I believe this question has been resolved. Please let us know if not!
