### ISSUE TITLE
Unable to scroll in output / Console

### ISSUE THREAD

**Issue by draco961** [Azure-Samples/digital-twins-explorer#235]
- Open Output
- Do a simple query: Query everything
- Unable to scroll down in the output

![image](https://user-images.githubusercontent.com/23629315/142891031-b3e33f45-2481-486e-9ea2-4b003f645baa.png)

**Comment by draco961** [comment]
I have added manually in the code web page "element.style = overflow: scroll" and it does the trick. But this in removed each time I refresh the page :p

![image](https://user-images.githubusercontent.com/23629315/142998008-bba98408-2169-4a40-a126-00a94123b627.png)

**Comment by ccrowley96** [comment]
Scrolling functionality in the output / console windows was added in #232.  This will be included in the the next feature roll out!

**Comment by ccrowley96** [comment]
@draco961 this is now fixed in both `main` and hosted explorer @ https://explorer.digitaltwins.azure.net/
