### ISSUE TITLE
Trying Sign In ... Unhandled Rejection (TypeError): Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by felixmondelo** [Azure-Samples/digital-twins-explorer#24]
I fill the Client ID, Tenant ID and ADT URL to connect, but when I press the "Connect" button I receive this error:

Unhandled Rejection (TypeError): Cannot read property 'on' of undefined
SignalRService.subscribe
C:/Projects/Azure_Digital_Twins__ADT__explorer/client/src/services/SignalRService.js:41

Do you know how to fix this problem? I attach a capture.
![Unhandled](https://user-images.githubusercontent.com/14011841/93463744-7824cc00-f8e8-11ea-9a14-24ceb1a50975.png)

**Comment by felixmondelo** [comment]
Solved in #14  adding https to ADT URL

**Comment by felixmondelo** [comment]
I add the https to the ADT URL and the error continues, but if I refresh, sometimes I can retrieve Model Views data, but continues with errors.

**Comment by jamescarpinter** [comment]
Thanks for reporting this issue. Are you able to share a little more about the repo steps? E.g. after you refresh the page, what do you click on next?

**Comment by jamescarpinter** [comment]
The authentication code has simplified considerably as part of the most recent release. I'll close this for now but please let us know if you're still running into problems getting connected.
