### ISSUE TITLE
Error in importing graph

### ISSUE THREAD

**Issue by felixmondelo** [Azure-Samples/digital-twins-explorer#25]
Hi, 

When I try upload a graph I receive the following error:

"Error in importing graph: ClientAuthError: AcquireToken_In_Progress: Error during login call - login is already in progress"

How can I solve this problem?

**Comment by jamescarpinter** [comment]
Thanks for reporting this issue! I can reproduce it so we'll work on getting it fixed. One potential workaround may be to run a query before running the import operation to ensure authentication completes first.

**Comment by jamescarpinter** [comment]
This issue should now be resolved. We believe multiple authentication processes were attempting to run in parallel causing this error. Please let us know if you are still running into the issue. Thanks again for reporting it.
