### ISSUE TITLE
ADT Explorer can't fetch models

### ISSUE THREAD

**Issue by avamade** [Azure-Samples/digital-twins-explorer#27]
No matter what I do I get this:
![image](https://user-images.githubusercontent.com/71514999/93612938-79312880-f9d0-11ea-8a15-bbcd31b5f5c9.png)

When I access the twin URL I get ERROR 404, not 401 or 400, so curious if DT service should be accessible this way or I should use another region for the deployment (currently EU-west).

SETUP:
Followed the setup instructions from: [https://docs.microsoft.com/en-us/azure/digital-twins/how-to-set-up-instance-portal](https://docs.microsoft.com/en-us/azure/digital-twins/how-to-set-up-instance-portal)
and [https://docs.microsoft.com/en-us/azure/digital-twins/quickstart-adt-explorer](https://docs.microsoft.com/en-us/azure/digital-twins/quickstart-adt-explorer)
and used the Web app permission with callback url set to http://localhost:3000 as suggested in readme.md for the ADT explorer.

The subscription is VS Professional and AD/user are under the same subscription.

Could you please help us with that, I'm not the only one having this problem.

**Comment by nightscape** [comment]
I think only EU-north is supported at the moment.

**Comment by avamade** [comment]
> I think only EU-north is supported at the moment.

Thank you!
I tried US-East, however even with this region it didn't work. Do you mean it works only with EU-north?

**Comment by avamade** [comment]
these locations are returned as valid by a powershell script provided my MS by the links above:
eastus
westus2
australiaeast
northeurope
westeurope
westcentralus

**Comment by avamade** [comment]
did anybody get the ADT explorer to work with the latest version of digital twin on one of these locations?

**Comment by avamade** [comment]
FIX: 
the correct role assignment should be created among other things, please double check if it equals 'Azure Digital Twins Owner (Preview)', could be the case it's Owner then it will not work as it was in my case.

PS command to do it is below:
az dt role-assignment create --dt-name [instance name]--assignee "[user name]"  --role "Azure Digital Twins Owner (Preview)"

**Comment by jamescarpinter** [comment]
In addition to improving the documentation, we'll look at how we can provide a better error message (i.e. if the user isn't logged in correctly).

**Comment by jamescarpinter** [comment]
The authentication code has simplified considerably as part of the most recent release, including adding improved error messages.
