### ISSUE TITLE
Empty contents array

### ISSUE THREAD

**Issue by khilscher** [Azure-Samples/digital-twins-explorer#28]
Digital Twins Explorer throws the following error when a model is uploaded containing an empty ```contents``` array. Note, the same model passes validation by the DTDL parser and can be successfully uploaded to ADT.
```
  {
    "@id": "dtmi:com:example:PizzaTopping;2",
    "@type": "Interface",
    "contents": [
    ],
    "@context": "dtmi:dtdl:context;2",
    "displayName": "PizzaTopping",
    "comment": "Class representing the toppings on a Pizza^^http://www.w3.org/2001/XMLSchema#string"
  }
```
![image](https://user-images.githubusercontent.com/13604100/94038776-1d75ef00-fd84-11ea-8083-6f3cd949f33f.png)

**Comment by jamiewilbraham** [comment]
This is has been addressed in master
![image](https://user-images.githubusercontent.com/13650672/112919828-509aa000-9164-11eb-8881-5cb4b1dddf10.png)
