### ISSUE TITLE
Error loading example model

### ISSUE THREAD

**Issue by gillermaney** [Azure-Samples/digital-twins-explorer#3]
I followed the readme installation instructions and encountered no errors.

On start up of adt-explorer, I get:

[HPM] Proxy created: /  -> /
i ｢wds｣: Project is running at http://192.168.1.117/
i ｢wds｣: webpack output is served from
i ｢wds｣: Content not from webpack is served from C:\Users\myname\digital-twins-explorer-master\client\public
i ｢wds｣: 404s will fallback to /
Starting the development server...
Compiled successfully!

You can now view adt-explorer in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://192.168.1.117:3000

However, when I load the example power system model or even a single file such as baseplant, I get the following error: "*** UploadError; Error "SyntaxError: unexpected token E in JSON at position 0" occured with parsing the response body - Error occured while trying to proxy to: localhost:3000/models? includeModelDefintion=true&api-version=2020-05-31-preview.

I used http://localhost:3000 for my ADT URL to sign in and the client app is running on localhost:3000.  Connect seems to work fine, but I get a spinner in the model view pane as soon as I log in and before running any query.  Eventually a very similar error as above pops up. "*** Error fetching models: Error; Error "SyntaxError: unexpected token E in JSON at position 0" occured with parsing the response body - Error occured while trying to proxy to: localhost:3000/models? includeModelDefintion=true&api-version=2020-05-31-preview.

PowerShell shows: 
[HPM] Error occurred while trying to proxy request /models?includeModelDefinition=true&api-version=2020-05-31-preview from localhost:3000 to / (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
or
[HPM] Error occurred while trying to proxy request /query?api-version=2020-05-31-preview from localhost:3000 to / (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

This happens on two different client machines.

**Comment by cschormann** [comment]
I sent some follow-up questions via email...

**Comment by cschormann** [comment]
Resolved in offline conversation, configuration issue
