### ISSUE TITLE
Object view not updating

### ISSUE THREAD

**Issue by SteveOss** [Azure-Samples/digital-twins-explorer#39]
I am running the explorer locally. If I update the state of a twin externally then refresh the explorer by re-running the query "SELECT * FROM digitaltwins", then in the Output window I see the updated state of the twin. However if I have the RHS object view panel open, this is not updated.

**Comment by jamiewilbraham** [comment]
Hi @SteveOss ,

This is fixed in the development branch - will leave open for now until merged into main

Thanks

**Comment by jamiewilbraham** [comment]
Closing as the fix is now in the new default main branch here: https://github.com/Azure-Samples/digital-twins-explorer

Thanks again for reporting!
