### ISSUE TITLE
Cannot upload an array of models containing in single .json file

### ISSUE THREAD

**Issue by nazar-kuzo** [Azure-Samples/digital-twins-explorer#41]
When I try to upload a single .json file containing the array of models, I get this error on the browser:

> *** Upload error: RestError: Operation failed as models provided was empty or of a type that is not supported.. Check that your Model Array contains at least one item and it is of a supported type. See link(http://aka.ms/ADTv2Models) for details.

After viewing the request payload to the server it explains why:
ADT-explorer expects to have a single model in the .json file since it grabs one or more .json files and pushes content (model)
into the internal array and sends it to the server. Since array of models is not flattened it results into invalid payload and upload fails.

Please add ability to upload the array of models containing in a single .json file which will simplify the process of uploading converted RDF/OWL models to ADT.

Thanks!

**Comment by jamescarpinter** [comment]
This capability has been added. JSON files containing an array of models can now be uploaded.
