### ISSUE TITLE
Add support of batch upload if model upload exceeds limit in 250 records

### ISSUE THREAD

**Issue by nazar-kuzo** [Azure-Samples/digital-twins-explorer#42]
When I try to upload more than 250 models it fails with the error:

> *** Upload error: RestError: The number of models you are trying to upload exceeds the supported limit of 250. Try breaking up the upload in smaller batches.

It would be great if you could detect this case and do upload in batches of 250 model to simplify the process of uploading models that exceeds that limit.

Thanks!

**Comment by jamiewilbraham** [comment]
This should now be resolved in the [main](https://github.com/Azure-Samples/digital-twins-explorer/tree/main) branch.

Thanks!
