### ISSUE TITLE
Model upload process should be improved

### ISSUE THREAD

**Issue by nazar-kuzo** [Azure-Samples/digital-twins-explorer#43]
I have a single json file with 450 models to be uploaded, since api is not allowing upload the array of models exceeding the 250 items I can split the array into batches during upload but there is a chance of having model referencing another model which is missing from this upload batch as the result - I cannot complete the upload at all.

There should be a step of building a model dependency graph before upload which will prioritize models to upload in batches without dependencies so the next batch upload will succeed based on already uploaded dependencies.

Thanks!

**Comment by jamiewilbraham** [comment]
This should now be resolved in the [main](https://github.com/Azure-Samples/digital-twins-explorer/tree/main) branch.

Thanks!
