### ISSUE TITLE
Docker config step missing? 400 reason: connect ECONNREFUSED

### ISSUE THREAD

**Issue by BillmanH** [Azure-Samples/digital-twins-explorer#54]
I was running the docker version of this twin explorer, and getting a 400 error from the Identity. 

**per the docs I did:**
* Access tokens enabled
* URI callback `http://localhost:3000` added

Application runs fine, however the credential issue below. 

```
AuthenticationError: ManagedIdentityCredential authentication failed.(status code 400).
More details:
request to http://169.254.169.254/metadata/identity/oauth2/token?resource=https%3A%2F%2Fdigitaltwins.azure.net&api-version=2018-02-01 failed, reason: connect ECONNREFUSED 169.254.169.254:80
    at ManagedIdentityCredential.<anonymous> (/usr/src/app/client/node_modules/@azure/identity/dist/index.js:1077:23)
    at Generator.throw (<anonymous>)
    at rejected (/usr/src/app/client/node_modules/@azure/identity/node_modules/tslib/tslib.js:112:69)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

* is it required to add `169.254.169.254` to the callback URI in the app, in addition to `localhost`?
* is there another place in the system setup where you need to add the DT credentials?

**Comment by BillmanH** [comment]
@joseba-altran : this is your `readme.md` addition. do you know if either of these are done in your local implementation?

* did you add the IP address of the identity token to your callback URI?
* are you populating any local files with tokens or IDs that make your call not anonymous?

**Comment by BillmanH** [comment]
Confirmed that I'm able to run the explorer outside of the container with `npm run start` from the client/src directory. It looks like the app is able to grab the `az login` credentials when the container is not.

**Comment by joseba-altran** [comment]
I can replicate the issue and would say that the problem with the authentication is related to the changes mentioned here:
https://github.com/Azure-Samples/digital-twins-explorer/commit/52f6de60a04d32776a626ff05b59ae99656a0154

I have manually tried to install the azure CLI and run `az login` within the docker image and that seems to work, will have to integrate that into the Dockerfile & update the instructions.

**Comment by joseba-altran** [comment]
Well, the following Dockerfile does appear to be working fine again. I'll try to brush it up a little bit (I'll also try to convert it into a multi-stage build in order to reduce the image size) and create a PR.

```dockerfile
FROM node:latest

# Create app directory
WORKDIR /usr/src/app/client

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY ./client/package*.json ./
WORKDIR /usr/src/app/client/src
RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
WORKDIR /usr/src/app
COPY . .

# Install the Azure CLI, which will be required for authentication
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# Notify that we want to expose port 3000
EXPOSE 3000
# Create startup script & start the app
WORKDIR /usr/src/app/client/src
RUN printf "#!/bin/sh\nset -e\naz login && npm run start" > startup.sh
RUN chmod 0755 startup.sh
ENTRYPOINT ["./startup.sh"]
```

**Comment by joseba-altran** [comment]
A quick update on this: I was trying to perform a multi-stage build, but keep getting memory errors when running `npm run build`. The following Dockerfile (similar to the previous one) does produce a working container, but the resulting image size is ~1.47GB. Of those:
- Azure CLI takes ~635MB
- The code + dependencies take up ~640MB

```dockerfile
FROM node:current-slim

# Install required dependencies
RUN apt-get update
RUN apt-get -y install curl python make g++

# Install the Azure CLI, which will be required for authentication
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# Create app directory
WORKDIR /usr/src/app/client

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY ./client/package*.json ./
WORKDIR /usr/src/app/client/src
RUN npm install

# Bundle app source
WORKDIR /usr/src/app
COPY . .
WORKDIR /usr/src/app/client/src

# Notify that we want to expose port 3000
EXPOSE 3000
# Create startup script & start the app
WORKDIR /usr/src/app/client/src
RUN printf "#!/bin/sh\nset -e\naz login && npm run start" > startup.sh
RUN chmod 0755 startup.sh
ENTRYPOINT ["./startup.sh"]
```

I could try other authentication approaches based on exposing environment variables to the container, but that would probably result in a poorer UX, so I'm going to create a PR with this `Dockerfile`.

**Comment by benbuckland** [comment]
Hi @joseba-altran, I am trying to get ADT Explorer going in docker, have used your Dockerfile but are still getting the "AuthenticationError: ManagedIdentityCredential authentication failed.(status code 400)." error.

Any suggestions?

**Comment by joseba-altran** [comment]
Hi @benbuckland, I also have multiple subscriptions so that should not be a problem.
Are you sure you have cleared any previous docker images? When run with this Dockerfile the container should ask you to enter a code at the microsoft oauth2 site; does that happen to you?

**Comment by benbuckland** [comment]
Hey @joseba-altran, I can see in docker desktop that I am running the latest image that I have built. I was getting the code in the build console and entering on the web but was still having issues after successfully going through that process.

Let me clear everything out and try again.

**Comment by BillmanH** [comment]
Confirmed that the `dockerfile` posted by @joseba-altran above works. Thanks a lot for including that!
