### ISSUE TITLE
ADT Explorer doesn't create twin instances with models having a fully qualified id for the "contents" or "properties" or "enumValues" or "schema" section

### ISSUE THREAD

**Issue by alinamstanciu** [Azure-Samples/digital-twins-explorer#57]
ADT Explorer doesn't create twin instances with models having a fully qualified id for the "contents" or "properties" or "enumValues" or "schema" section
· "dtmi:dtdl:property:contents;2"
· "dtmi:dtdl:property:properties;2"
· "dtmi:dtdl:property:enumValues;2"
· "dtmi:dtdl:property:schema;2"

**Comment by cschormann** [comment]
Should be fixed in main now
