### ISSUE TITLE
ADT Explorer doesn't create twin instances with models having non-array in contents section

### ISSUE THREAD

**Issue by alinamstanciu** [Azure-Samples/digital-twins-explorer#58]
ADT Explorer doesn't create twin instances with models having non-array in contents section
If contents sections would have a single item and they are omitting the array identifier "[]" , then ADT Explorer is not able to create a twin instance.

**Comment by alinamstanciu** [comment]
Also, · If "contents" section doesn't have anything to be added, e.g. an interface inherits from others, but doesn't add anything extra, "contents" section has to be an empty array, otherwise ADT-Explorer doesn't create twin instances

**Comment by cschormann** [comment]
Should be fixed in main now
