### ISSUE TITLE
Model Filtering

### ISSUE THREAD

**Issue by gillermaney** [Azure-Samples/digital-twins-explorer#6]
Feature Request: I realize that you can use SELECT * FROM DIGITALTWINS WHERE IS_OF_MODEL('dtmi:sample:thing;1') to filter based on models.  But this is such a common requirement that it would be nice for the GUI to have a drop down list box or tree control that allowed you to pick a model that would filter data in the model and graph view.

**Comment by cschormann** [comment]
Thanks for the request. 

You can filter the model view today by entering any partial name in the search box. The filter in the model view currently operates on the DTMI, not the display name.

**Comment by rinisbet** [comment]
Ask is: highlight twins in the twin graph by selecting a model in the models pane

**Comment by rinisbet** [comment]
moving to internal backlog
