### ISSUE TITLE
fail to install on windows

### ISSUE THREAD

**Issue by lucarv** [Azure-Samples/digital-twins-explorer#79]
Following the tutorial on https://docs.microsoft.com/en-us/samples/azure-samples/digital-twins-explorer/digital-twins-explorer/

Fail to install dependencies on a Windows machine.

 ###\client>npm i

> adt-explorer@0.1.0 preinstall C:\Users\eksko\OneDrive\work\repos\adtxplorer\client
> npx npm-force-resolutions

npx: installed 5 in 2.216s

> node-sass@4.14.1 install C:\Users\eksko\OneDrive\work\repos\adtxplorer\client\node_modules\node-sass
> node scripts/install.js

internal/fs/utils.js:298
    throw err;
    ^

Error: UNKNOWN: unknown error, read
    at Object.readSync (fs.js:581:3)
    at tryReadSync (fs.js:357:20)
    at Object.readFileSync (fs.js:386:19)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1271:22)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (C:\Users\eksko\OneDrive\work\repos\adtxplorer\client\node_modules\glob\glob.js:51:18)
    at Module._compile (internal/modules/cjs/loader.js:1251:30) {
  errno: -4094,
  syscall: 'read',
  code: 'UNKNOWN'
}
npm WARN eslint-config-react-app@5.2.1 requires a peer of @typescript-eslint/eslint-plugin@2.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.2.1 requires a peer of @typescript-eslint/parser@2.x but none is installed. You must install peer dependencies yourself.
npm WARN jsoneditor-react@3.0.0 requires a peer of jsoneditor@^7.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\react-scripts\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.14.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.14.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by jamescarpinter** [comment]
Thanks for reporting this issue. I've just run through a fresh install on a Windows 10 and unfortunately I was unable to replicate this issue. Futhermore, I haven't been able to identify any immediate leads on what might be causing it ☹️. As a first step, I'd suggest removing the `node_modules` folder and trying the install again. Another option might be to try installing the sample outside of your OneDrive directory (as I'm not aware of our team trying an install within a synced folder before).

**Comment by lucarv** [comment]
one drive was the culprit

**Comment by jamescarpinter** [comment]
Thanks for the update. I'll close this issue now but please let us know if you run into any other issues.
