### ISSUE TITLE
Installation fails (username contains space)

### ISSUE THREAD

**Issue by christianhidber** [Azure-Samples/digital-twins-explorer#84]
"npm install" failed on my win10 machine where my username contains a space (eg "john doe").
installation with a "space-less" username worked fine.

[2020-12-17T14_31_33_435Z-debug.log](https://github.com/Azure-Samples/digital-twins-explorer/files/5710192/2020-12-17T14_31_33_435Z-debug.log)

**Comment by jamescarpinter** [comment]
Thanks for reporting this issue. We will include a note in the readme as a short term fix.

I believe this issue has already been reported in the [npm-force-resolutions repo](https://github.com/rogeriochaves/npm-force-resolutions/issues/17). Our goal is to remove this dependency in due course once we have a long term fix for the underlying security issue.

**Comment by jamiewilbraham** [comment]
HI @christianhidber 

Due to the dependency above - for now, we have added a note to the documentation in the development branch (step 4). 
https://github.com/Azure-Samples/digital-twins-explorer/blob/development/README.md#running-adt-explorer-locally

Will close once merged to main
 
thanks

**Comment by jamiewilbraham** [comment]
Closing as the fix is now in the new default main branch here: https://github.com/Azure-Samples/digital-twins-explorer

Thanks again for reporting!
