### ISSUE TITLE
TypeError when selecting a node in distributionGrid example

### ISSUE THREAD

**Issue by tommmc** [Azure-Samples/digital-twins-explorer#85]
![image](https://user-images.githubusercontent.com/39488651/102605493-43115b00-411d-11eb-8868-2e61eba0ce68.png)

Issue found when selecting nodes in the examples.

**Comment by jamiewilbraham** [comment]
Hi @tommmc,

This should be now fixed in master. I tested the distributed grid example and no longer get the exception above. 

Thanks
