### ISSUE TITLE
Augment error message with more detailed information on instance data spreadsheet import failure

### ISSUE THREAD

**Issue by gillermaney** [Azure-Samples/digital-twins-explorer#9]
Feature request: Today if instance data import fails,  the error message is: “Twin relationship does not align with the model"

If possible, it would be nice to provide information about why this failure occurred.  See attached for an example when importing into a ADT repository.

[EY_ModelingQuestion.zip](https://github.com/Azure-Samples/digital-twins-explorer/files/5030799/EY_ModelingQuestion.zip)
.

**Comment by rinisbet** [comment]
moving to internal backlog
