### ISSUE TITLE
'console' patchtwin command not working

### ISSUE THREAD

**Issue by stevebus** [Azure-Samples/digital-twins-explorer#90]
I'm trying to use the 'patchtwin' command in the adt-explorer console to update a twin property.  I have a simple property defined in my model like this..

   {
      "@type": "Property",
      "name": "avgHumidity",
      "schema": "double"
    },

and a twin instance that leverages that property.

![image](https://user-images.githubusercontent.com/11857454/104642529-a5a03d00-5670-11eb-89c8-7383cb5842bb.png)

When i try to update the 'avgHumidity' property via the patchtwin command, I always get the error below...

![image](https://user-images.githubusercontent.com/11857454/104654772-49deaf80-5682-11eb-8ed5-fa235710016b.png)

I've tried several combinations of referencing the property, setting the value, etc.  Have also tried it against multiple twin instances.  Same error every time (Property doesn't exist).

updating the same property in the same twin instance via the AZ CLI works fine as seen below.

![image](https://user-images.githubusercontent.com/11857454/104654953-8f9b7800-5682-11eb-8f8c-e9d098a8faf8.png)

**Comment by jamiewilbraham** [comment]
Hi @stevebus ,

This should be now fixed in the development branch. Will close when merged to main.

![image](https://user-images.githubusercontent.com/13650672/112926049-5e095780-916f-11eb-9ba0-80ee30fc15ff.png)

Thanks

**Comment by jamiewilbraham** [comment]
Closing as the fix is now in the new default main branch here: https://github.com/Azure-Samples/digital-twins-explorer

Thanks again for reporting!
