### ISSUE TITLE
Enumerations do not work

### ISSUE THREAD

**Issue by Haigutus** [Azure-Samples/digital-twins-explorer#91]
When enumeration is defined, only the first value of enumeration is accepted

Example 1.
Issue: could not change from ExtraHighVolatge to HighVoltage neither via UI or API. In UI it just falls back to the first enumeration value and API gives an error that twin does not match schema.
data_model: https://github.com/Azure-Samples/digital-twins-explorer/blob/master/client/examples/PowerLine.json
![image](https://user-images.githubusercontent.com/11408965/104778091-78917e80-5785-11eb-8694-9972d4fd4b3f.png)

Example 2.
Issue: Cant change phase code from http://iec.ch/TC57/2013/CIM-schema-cim16#PhaseCode.ABCN to anything else.
data_model: https://github.com/Haigutus/USVDM/blob/master/Tools/RDF_PARSER/entsoe_v2.4.15_2014-08-07_DTDL_V2/Terminal.json
![image](https://user-images.githubusercontent.com/11408965/104778727-8398de80-5786-11eb-94d4-adbb33cbd403.png)

**Comment by jamescarpinter** [comment]
Thanks for reporting this issue! We'll dig into it.

**Comment by jamiewilbraham** [comment]
Hi @Haigutus,

We have fixed the issue updating enums in the development branch. You should be able to update using the example above.

NOTE: We are working on a better UX experience for enums - but for now a string value will work.

![image](https://user-images.githubusercontent.com/13650672/112927833-1b954a00-9172-11eb-9574-ed0feb999e7f.png)

**Comment by jamiewilbraham** [comment]
Closing as the fix is now in the new default main branch here: https://github.com/Azure-Samples/digital-twins-explorer

Thanks again for reporting!
