### ISSUE TITLE
unable to install with python 3.8.3

### ISSUE THREAD

**Issue by ChristianBeier** [Azure-Samples/digital-twins-explorer#93]
When I running npm install the build fails at 
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\...\Programs\Python\Python38-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:333:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1063:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\ADT\\ADT_explorer\\client\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\ADT\ADT_explorer\client\node_modules\node-sass
npm ERR! gyp ERR! node -v v15.5.0                                                                                                                                                                                 npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

Seems related to node-gyp v3.8.0 dependency of node-sass (<5) what supports only python2 (EOL)
https://github.com/sass/node-sass/issues/3013
https://github.com/sass/node-sass/issues/2877
Also interesting [Libsaas and Node-Saas are deprecated](https://sass-lang.com/blog/libsass-is-deprecated). Not better to switch to sass as recommended?

**Comment by ChristianBeier** [comment]
managed to run it with dart-saas https://github.com/sass/dart-sass/releases/tag/1.32.4

**Comment by ReneHezser** [comment]
Thanks for the pull request @ChristianBeier. I was stumbling across the same problem.

In the package.json change this:
`"node-sass": "^4.14.1",` --> `"sass": "^1.32.4",`

**Comment by jamescarpinter** [comment]
This fix is now in the `development` branch. Once we've finished our test pass, it'll be merged into `master`. Thanks!

**Comment by jamiewilbraham** [comment]
Closing as the fix is now in the new default main branch here: https://github.com/Azure-Samples/digital-twins-explorer

Thanks again for reporting!
