### ISSUE TITLE
Unhandled Rejection when importing graph file missing "relationships" element

### ISSUE THREAD

**Issue by briancr-ms** [Azure-Samples/digital-twins-explorer#95]
When importing a graph file that's missing the digitalTwinsGraph/relationships element, ADT Explorer fails with an Unhandled Rejection error.

Error:
[UnhandledRejection.pdf](https://github.com/Azure-Samples/digital-twins-explorer/files/5896189/UnhandledRejection.pdf)

Input:
```
{
  "digitalTwinsFileInfo": {
    "fileVersion": "1.0.0"
  },
  "digitalTwinsGraph": {
    "digitalTwins": []
  },
  "digitalTwinsModels": []
}
```

**Comment by jamiewilbraham** [comment]
HI @briancr-ms ,

This should now be addressed in the development branch.

**Comment by jamiewilbraham** [comment]
Closing as the fix is now in the new default main branch here: https://github.com/Azure-Samples/digital-twins-explorer

Thanks again for reporting!
