### ISSUE TITLE
minor typo in CUSTOM_AUTH_ERROR_MESSAGE

### ISSUE THREAD

**Issue by pchevallier** [Azure-Samples/digital-twins-explorer#96]
In client/src/services/Constant.js:
We have:
`"....on your host machine,  or example by running..."`
but it should be:
`"....on your host machine,  for example by running..."`

**Comment by jamiewilbraham** [comment]
Hi @pchevallier ,

this is fixed in the development branch https://github.com/Azure-Samples/digital-twins-explorer/commit/c3b1d5185d07aa1505f8b6f2c6527fdbfc475ec0

will close once merged

**Comment by jamiewilbraham** [comment]
Closing as the fix is now in the new default main branch here: https://github.com/Azure-Samples/digital-twins-explorer

Thanks again for reporting!
