### ISSUE TITLE
Authentication Issue in Local Machine

### ISSUE THREAD

**Issue by aliyevmirzakhan** [Azure-Samples/digital-twins-explorer#97]
Hi,
I am new to ADT, I was exploring the ADT Explorer, but ran into some authentication issue, and apparently cannot workaround. I follow the steps mentioned in the documentation about creating an instance, authentication, role assignment etc. Despite that I get `CustomAuthErrorMessage` each time I launch the sample client application:

![image](https://user-images.githubusercontent.com/47746478/107381758-9cd44700-6b08-11eb-90c1-1750b0225b9d.png)

I have my Azure account logged in my local machine:
![image](https://user-images.githubusercontent.com/47746478/107383507-80390e80-6b0a-11eb-9365-8b3efb97d745.png)

and in VS code:
![image](https://user-images.githubusercontent.com/47746478/107382030-de64f200-6b08-11eb-99f9-e8d9c135d880.png)

I am using the same account that I created the ADT instance, and I have the owner role over the instance (inherited).

Despite all, I cannot still figure out what is wrong. Would be happy if anyone helps. Thanks in advance

**Comment by klcampbell6502** [comment]
I have exactly the same problem, logged in via az login and confirmed that the subscription is shown appropriately, but still get the authentication error. I am both the owner and the "system administrator" of the ADT instance I'm trying to connect to

**Comment by mschwerdtfeger** [comment]
Adding the role **Azure Digital Twins Data Owner** to the user helped in one of my cases.

**Comment by aliyevmirzakhan** [comment]
Hi msc

> Adding the role **Azure Digital Twins Data Owner** to the user helped in one of my cases.

This is life saver. Thanks a lot
